language: python
python:
- '3.6'
install:
  - pip install -r requirements.txt
script:
- python -m unittest discover
notifications:
  email:
  - jtmoore@us.ibm.com
before_install:
  - openssl aes-256-cbc -K $encrypted_be1cb1c3f350_key -iv $encrypted_be1cb1c3f350_iv
    -in .env.enc -out .env -d
